[package]
name = "cryptography-openssl"
version = "0.1.0"
authors = ["The cryptography developers <cryptography-dev@python.org>"]
edition = "2021"
publish = false
# This specifies the MSRV
rust-version = "1.65.0"

[dependencies]
cfg-if = "1"
openssl = "0.10.64"
ffi = { package = "openssl-sys", version = "0.9.101" }
foreign-types = "0.3"
foreign-types-shared = "0.1"
